/**
 * Parser for `index-full.json` — the authoritative, always-fresh
 * GitHub-discovered repo inventory output by the `update-index.yml`
 * workflow.
 *
 * Compared to `repo-locations.md`:
 *   - index-full.json is regenerated by GitHub Actions on every build and
 *     always reflects the current GitHub state seen by REPO_ACCESS_TOKEN.
 *   - repo-locations.md is regenerated only by the local MCP server's
 *     `sync_repos` tool, so can drift behind index-full.json.
 *
 * This module exists so the taxonomy inference script can fall back to
 * the JSON source when the markdown source is stale or unavailable.
 *
 * Note: index-full.json does NOT include local filesystem paths (it's
 * built in CI without knowledge of the user's machine). Local paths come
 * from repo-locations.md — hence the merge step in `combineRepoSources`.
 */

import * as fs from 'fs/promises';
import { RepoEntry, RepoStatus } from './parseRepoLocations.js';

interface IndexFullShape {
  buildTime?: string;
  repos: Array<{
    name: string;
    description?: string;
    githubUrl?: string;
    languages?: string[];
    lastCommitDate?: string;
    status?: 'synced' | 'local-only' | 'github-only';
    visibility?: 'public' | 'private';
    sentinels?: {
      hasPackageManifest?: boolean;
      hasDeployConfig?: boolean;
      hasReadme?: boolean;
      hasClaudeMd?: boolean;
      hasCi?: boolean;
      hasTests?: boolean;
      hasEnvExample?: boolean;
      sourceFileCount?: number;
    };
  }>;
}

export interface IndexFullRepo extends RepoEntry {
  description?: string;
  lastCommitDate?: string;
  ghVisibility?: 'public' | 'private';
  sentinels?: IndexFullShape['repos'][number]['sentinels'];
}

export async function parseIndexFull(filePath: string): Promise<IndexFullRepo[]> {
  const raw = await fs.readFile(filePath, 'utf-8');
  const data = JSON.parse(raw) as IndexFullShape;

  return (data.repos ?? []).map((r) => ({
    name: r.name,
    githubUrl: r.githubUrl,
    status: (r.status ?? 'synced') as RepoStatus,
    languages: r.languages,
    description: r.description,
    lastCommitDate: r.lastCommitDate,
    ghVisibility: r.visibility,
    sentinels: r.sentinels,
  }));
}

export async function findIndexFull(explicitPath?: string): Promise<string | null> {
  const candidates = [
    explicitPath,
    process.env.PRIVATE_CONTENT_DIR
      ? `${process.env.PRIVATE_CONTENT_DIR}/web/public/data/index-full.json`
      : undefined,
    `${process.cwd()}/../code-wiki-content/web/public/data/index-full.json`,
    `${process.cwd()}/private-content/web/public/data/index-full.json`,
  ].filter((p): p is string => typeof p === 'string');

  for (const candidate of candidates) {
    try {
      await fs.access(candidate);
      return candidate;
    } catch {
      /* try next */
    }
  }
  return null;
}
